name: Build for Raspberry Pi 3B+ (64-bit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build in ARM64 container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binary in arm64 container
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          outputs: type=local,dest=./output
          file: .github/Dockerfile.arm64
