name: Build for Raspberry Pi 3B+ (64-bit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Cross Compile for linux/arm64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build binary for Raspberry Pi (linux/arm64)
        env:
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
          CGO_ENABLED: 1
        run: |
          go build -v -o bin/wavestreamer ./...

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: wavestreamer-linux-arm64
          path: bin/wavestreamer
