name: Build for Raspberry Pi 3B+

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            autoconf \
            libtool \
            wget \
            gcc-aarch64-linux-gnu

      - name: Cross-compile PortAudio for aarch64
        run: |
          mkdir -p build/portaudio
          cd build
          wget http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz
          tar xzf pa_stable_v190700_20210406.tgz
          cd portaudio
          ./configure --host=aarch64-linux-gnu --prefix=$PWD/../portaudio-install --disable-shared
          make -j$(nproc)
          make install

      - name: Build Go binary for arm64
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
          PKG_CONFIG_PATH: ${{ github.workspace }}/build/portaudio-install/lib/pkgconfig
          CGO_CFLAGS: -I${{ github.workspace }}/build/portaudio-install/include
          CGO_LDFLAGS: -L${{ github.workspace }}/build/portaudio-install/lib -lportaudio
        run: |
          go build -v -o wavestreamer ./wavestreamer.go

      - name: Verify linkage
        run: |
          file wavestreamer
          ldd wavestreamer || true
          strings wavestreamer | grep -i portaudio || true

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: wavestreamer-arm64
          path: wavestreamer
