name: Cross-compile for Raspberry Pi (ARMv7)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-pi:
    runs-on: ubuntu-latest

    container: debian:bullseye

    steps:
      - name: Enable armhf and install dependencies
        run: |
          dpkg --add-architecture armhf
          apt-get update
          apt-get install -y \
            gcc-arm-linux-gnueabihf \
            pkg-config \
            libportaudio2:armhf \
            libportaudio-dev \
            libasound2-dev:armhf \
            libasound2:armhf \
            golang-go ca-certificates curl git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for Raspberry Pi
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 7
          CGO_ENABLED: 1
          CC: arm-linux-gnueabihf-gcc
          GO111MODULE: on
        run: |
          mkdir -p bin
          go build -o bin/wavestreamer-linux-armv7

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: wavestreamer-linux-armv7
          path: bin/wavestreamer-linux-armv7
