name: Cross-compile for Raspberry Pi (ARMv7)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build-pi:
    name: Build for Raspberry Pi (ARMv7)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go from go.mod
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install cross compiler and ARM PortAudio + ALSA
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt update
          sudo apt install -y \
            gcc-arm-linux-gnueabihf \
            libportaudio2:armhf \
            libportaudio-dev:armhf \
            libasound2-dev:armhf

      - name: Cross compile with cgo for ARMv7
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 7
          CGO_ENABLED: 1
          CC: arm-linux-gnueabihf-gcc
        run: |
          mkdir -p bin
          go build -o bin/wavestreamer-linux-armv7

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: wavestreamer-linux-armv7
          path: bin/wavestreamer-linux-armv7
