name: Build for Raspberry Pi 3B+

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            autoconf \
            libtool \
            wget \
            gcc-aarch64-linux-gnu

      # For cross compiling we need to manually build both ALSA...
      - name: Download and build ALSA-lib for aarch64
        run: |
          mkdir -p build/alsa
          cd build/alsa
          wget https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.10.tar.bz2
          tar xjf alsa-lib-1.2.10.tar.bz2
          cd alsa-lib-1.2.10
          ./configure --host=aarch64-linux-gnu --prefix=$PWD/../alsa-install --enable-shared --disable-static
          make -j$(nproc)
          make install
          find build/alsa-install/lib
          ls -l ../alsa-install/lib/libasound.so*

      # ... and PortAudio for arm64
      - name: Download and build PortAudio with ALSA support for aarch64
        run: |
          mkdir -p build/portaudio
          cd build
          wget http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz
          tar xzf pa_stable_v190700_20210406.tgz
          cd portaudio
          ./configure --host=aarch64-linux-gnu \
            --prefix=$PWD/../portaudio-install \
            --with-alsa \
            --enable-shared \
            --disable-static \
            CFLAGS="-I$PWD/../alsa-install/include" \
            LDFLAGS="-L$PWD/../alsa-install/lib"
          make -j$(nproc)
          make install

      - name: Build Go binary for arm64
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
          PKG_CONFIG_PATH: ${{ github.workspace }}/build/portaudio-install/lib/pkgconfig
          LD_LIBRARY_PATH: ${{ github.workspace }}/build/portaudio-install/lib
          CGO_CFLAGS: -I${{ github.workspace }}/build/portaudio-install/include
          ALSA_LIB: ${{ github.workspace }}/build/alsa-install/lib
          PA_LIB: ${{ github.workspace }}/build/portaudio-install/lib
          CGO_LDFLAGS: "-L${{ env.PA_LIB }} -L${{ env.ALSA_LIB }} -lportaudio -lasound"
        run: |
          go build -v -o wavestreamer ./wavestreamer.go

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: wavestreamer-arm64
          path: wavestreamer
